### ISSUE TITLE
[Discussion] Should we rewrite the project in F#?

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/wpf-math#111]
_(I've decided to open new issue in answer to this comment from @charlesroddie: https://github.com/ForNeVeR/wpf-math/issues/43#issuecomment-361027638.)_

@charlesroddie well, yeah, most (if not all) of the current contributors know F# and personally I am very positive about it (up to the point I actually contribute to F# compiler [a little bit](https://github.com/Microsoft/visualfsharp/commits?author=ForNeVeR)). Although I'm not sure if we actually want to rewrite the WPF-Math in F#, and here's why:

1. **WPF is a very C#-centric technology.** One could use WPF with F# (and I had a couple of WPF projects in F#), but the experience is far from "native". Writing a WPF project in F# will create some (solvable) technical difficulties.
   - Yes, we're slowly moving towards cross-platform world, and we have plans to add support for some technologies alternative to WPF (SkiaSharp, Avalonia), although I think that WPF stuff (or maybe UWP, who knows?) will be a major part of our code for a long time from now.
2. It means that **we could expect most of the contributors to a WPF library to be familiar with C#.** The same cannot be said about F#, sadly. Yes, we're in an interesting position here, because WPF-Math is a project for LaTeX specialists (mainly scientists I think), and they seem to be, let's say, more open-minded than "ordinary" WPF developers. Although I still think that knowing F# will be a barrier for potential contributors. And I **love** contributors who help me to develop the project, and I **hate** creating any barriers for them.

These're the reasons I still want to develop WPF-Math in C# and I'd prefer not to rewrite it in F#. Please understand my position: I'm not being closed for new technologies (in fact, it was me who decided to write the unit tests in F# here, and I prefer F# over C# in most of my personal projects these days), I'm just trying to be objective. **I think that it'll be good for this project to be developed in C#.** Although I'm open for discussion. If anyone have their own opinion: let's discuss!

/cc @alexreg @gsomix @nocturnals @charlesroddie

_(This discussion isn't limited to the project contributors; feel free to participate in it if you have something to say.)_

**Comment by charlesroddie** [comment]
Hi @ForNeVeR . At the moment this is a personal project and I am only asking for help to understand the existing code, before you have it documented.

The project may fail because the code is too object oriented, I cannot simplify the cyclic dependencies and convert the existing structures which rely on mutability and inheritance.

If it succeeds then there should be a linear structure (perhaps a discriminated union data structure for representing the formula structure, one for representing how it will be displayed, and then a rendering layer).

It would make sense to have this discussion at that point, once you can see the F# code. If you like it you can decide whether to switch the project over, based of the affinity of F# vs C# for the task, likelihood of getting contributors, etc.. If you don't do that, no problem: I will keep the F# project separate.

I do think that WPF is a likely to be a red herring but it will be a while before I get round to the rendering layer.

**Comment by nocturnals** [comment]
@charlesroddie I've been put in "cc" in this discussion by @ForNeVeR for alternative viewpoints (I guess? :) )

The origin of this discussion was documenting the source code for developers. If you fork this project and use f#, I think this will help us. I've been thinking of using c++ to render math inside a 3d engine.  Suppose you develop an alternative to this engine in F# and I do the same for c++. Maybe the lessons learned can be implemented in a more general design?

Instead of you only copying and porting your code to F# (and me doing the same for c++), we try to construct several uml diagrams from which the source code (in whatever language) can be reconstructed. I'm not committed to uml diagrams, so feel free to suggest alternatives. The idea would be to push changes upstream independent of programming language.

I'm hoping that the diagrams & notes will help developers in navigating the source code (your original request) and help them differentiate between what is: parsing latex. layout, rendering when reading the source code (IIRC).

PS: I have some specifics in mind, but this post is already getting too long :)

**Comment by charlesroddie** [comment]
@nocturnals Your post disappeared, please repost!

**Comment by charlesroddie** [comment]
This is my Atom. I _think_ that a LaTeX string should be parsable into one of these. Then a function can convert an Atom into a Box, which describes how to render it. Does that sound right?

```
[<RequireQualifiedAccess>]
type Atom =
    /// Atom representing horizontal row of other atoms, separated by glue.
    | Row of Atom list
    /// Atom representing single character in specific text style.
    | Char of char * textStyle: string option
    /// Atom representing character that does not depend on text style.
    | FixedChar of c:char * fontId:int
    /// Atom representing base atom with accent above it.
    | Accented of Atom * Symbol
    /// Atom representing big delimeter (e.g. brackets).
    | BigDelimiter of delimiter:Atom * size:int
    /// Atom representing big operator with optional limits.
    | BigOperator of baseAtom:Atom * upperLimit:Atom * lowerLimit:Atom
    /// Atom representing base atom surrounded by delimeters.
    | Fenced of baseAtom:Atom * leftDelimiter:Symbol * RightDelimiter:Symbol
    /// Atom representing fraction, with or without separation line.
    | Fraction of numerator:Atom * denominator:Atom // * nAlign:TexAlignment * dAlign:TexAlignment
    /// Atom representing other atom with horizontal rule above it.
    | Overlined of baseAtom:Atom
    /// Atom representing scripts to attach to other atom.
    | Scripts of baseAtom:Atom
    /// Atom representing whitespace.
    | Space of width:float<mu> * height:float<mu>
    /// Atom representing other atom that is not rendered.
    | Phantom of baseAtom:Atom * useWidth:bool * useHeight:bool * useDepth:bool
    /// Atom representing other atom with custom left and right types.
    | Typed of atom:Atom * leftType:TexAtomType * rightType:TexAtomType
    /// Atom representing single character that can be marked as text symbol.
    | CharSymbol of isTextSymbol:bool
    /// Atom representing symbol (non-alphanumeric character).
    | Symbol of name:char * TexAtomType * isDelimiter:bool
    /// Atom representing other atom with delimeter and script atoms over or under it.
    | OverUnderDelimiter of baseAtom:Atom * script:Atom * Symbol * kern:float<mu> * over:bool
    /// Atom representing other atom that is underlined.
    | Underlined of baseAtom:Atom
    /// Atom representing other atom with atoms optionally over and under it.
    | UnderOver of baseAtom:Atom * underOver:Atom * underOverSpace:float<mu>
    /// Atom representing other atom vertically centered with respect to axis.
    | VerticallyCentered of atom:Atom
    /// Atom representing radical (nth-root) construction.
    | Radical of baseAtom:Atom * degreeAtom:Atom

    /// gets the left and right types of children or the type of the atom itself if it childless
    member t.GetLR: TexAtomType * TexAtomType =
        match t with
        | Row x -> x.Head.GetLeftType, List.last(x).GetRightType
        | BigDelimiter (a,_) | BigOperator (a,_,_) | Phantom (a,_,_,_)  | Scripts a
            -> a.GetLR
        | Fenced (_,l,r) -> TexAtomType.Opening, TexAtomType.Closing
        | Typed(_,l,r) -> l,r
        | _ -> t.Type, t.Type
    member t.GetLeftType  = t.GetLR |> fst
    member t.GetRightType = t.GetLR |> snd
    member t.Type = ...
```

**Comment by alexreg** [comment]
Apart from the solid points you make, @ForNeVeR, I don't feel F# has gained enough traction generally to warrant a rewrite. It might get harder and harder to maintain. Writing components of it (like the testing, which we already do) would be no problem, however.

**Comment by ForNeVeR** [comment]
@charlesroddie yes, that looks pretty much like I imagined. Seems like you're doing it right :)

**Comment by gsomix** [comment]
My 2c. I personally prefer C# for general purpose libraries, just make sure it works nicely for F# users too, i.e. no OOP-inheritance-based API, support for records/du and so on.

**Comment by alexreg** [comment]
@gsomix This can be achieved by a mixture of taking out the explicit OO aspects of the library and writing some thin shims for F#, I feel.

**Comment by ForNeVeR** [comment]
Alright, I believe we've decided to not rewrite the project in F#. Thanks for the discussion!
