### ISSUE TITLE
Sample expression started to fail in version 0.9

### ISSUE THREAD

**Issue by VassilievVV** [ForNeVeR/wpf-math#271]
Sample expression (one on description page of this project) started to fail in version 0.9, it worked in version 0.8:

L = \int_a^b \sqrt[4]{ \left| \sum_{i,j=1}^ng_{ij}\left(\gamma(t)\right) \left[\frac{d}{dt}x^i\circ\gamma(t) \right] \left{\frac{d}{dt}x^j\circ\gamma(t) \right} \right|}dt

**Comment by ForNeVeR** [comment]
Yep, this is definitely a bug. Thanks for reporting! I'll take a look ASAP.

**Comment by ForNeVeR** [comment]
Well, I'm not so sure already. `\left{` and `\right}` we've been able to parse have been considered bugs of our implementations; please use `\left\{` and `\right\}` for this.

But during the investigation, I've been able to spot a couple of other issues including several parser crashes. I'll create separate issues for these.

**Comment by ForNeVeR** [comment]
Thanks for reporting, I've created issues #272 and #273 with more focused descriptions. This particular issue (not being able to parse the formula you've mentioned) isn't considered as issue, because `\left{` and `\right}` should be replaced by `\left\{` and `\right\}`, according to other TeX implementations.

Thanks for reporting, anyway!

I'll update the screenshot on the project page to not confuse anyone.
