### ISSUE TITLE
OverUnderBox ctor may dereference scriptBox parameter if it's null

### ISSUE THREAD

**Issue by ygra** [ForNeVeR/wpf-math#275]
Noticed while trying to add C# 8 nullability information:

```
            this.Height = baseBox.Height + (over ? delimeterBox.Width : 0) +
                (over && scriptBox != null ? scriptBox.Height + scriptBox.Depth + kern : 0);
            this.Depth = baseBox.Depth + (over ? 0 : delimeterBox.Width) +
                (!over && scriptBox == null ? 0 : scriptBox.Height + scriptBox.Depth + kern);
```

The lower two lines look fishy and the condition may have indended to use `||` instead, but I can't tell for sure.

**Comment by ForNeVeR** [comment]
Thanks! This is, indeed, a bug. Fortunately though, `OverUnderBox` itself doesn't seem to be used much across the code: most of the usages are supposed to come from `PredefinedTexFormulas.xml` via reflection, and it never calls the methods that generate `OverUnderBox`es.

This will be fixed by #276.
